CREATE TABLE [dbo].[cxc_OrdenServicio] (
    [IdServicio]        INT             NOT NULL,
    [FechaRegistro]     DATETIME        NOT NULL,
    [IdCliente]         INT             NOT NULL,
    [Rfc]               VARCHAR (16)    NULL,
    [Cliente]           VARCHAR (80)    NOT NULL,
    [IdEmpresa]         INT             NOT NULL,
    [Empresa]           VARCHAR (80)    NOT NULL,
    [TipoSolicitud]     INT             NOT NULL,
    [FechaInicio]       DATETIME        NOT NULL,
    [FechaTermino]      DATETIME        NOT NULL,
    [Importe]           DECIMAL (18, 2) NOT NULL,
    [Periodos]          INT             NOT NULL,
    [TipoPeriodo]       INT             NOT NULL,
    [CondicionPago]     VARCHAR (64)    NOT NULL,
    [CondicionPagoDias] INT             NULL,
    [Proyecto]          VARCHAR (100)   NULL,
    [TipoMoneda]        VARCHAR (8)     NOT NULL,
    [IdCatServicio]     INT             NULL,
    [Servicio]          VARCHAR (100)   NULL,
    [Descripcion]       VARCHAR (128)   NULL,
    [Anotaciones]       VARCHAR (255)   NULL,
    [IdUsr]             INT             NOT NULL,
    [UnidadNegocio]     INT             NOT NULL,
    [CteSolomon]        VARCHAR (16)    NULL,
    [Contrato]          INT             NOT NULL,
    [EnviaCorreoClte]   INT             NULL,
    [Estado]            INT             NOT NULL,
    [Especial]          INT             NULL,
    CONSTRAINT [PK_cxc_OrdenServicio] PRIMARY KEY CLUSTERED ([IdServicio] ASC)
);

