CREATE TABLE [dbo].[cxc_OrdenFactura] (
    [IdServicio]          INT             NOT NULL,
    [IdOrdenFactura]      INT             NOT NULL,
    [FechaInicio]         DATETIME        NULL,
    [IdCliente]           INT             NOT NULL,
    [Rfc]                 VARCHAR (16)    NULL,
    [Cliente]             VARCHAR (80)    NOT NULL,
    [IdEmpresa]           INT             NOT NULL,
    [Empresa]             VARCHAR (80)    NOT NULL,
    [TipoSolicitud]       INT             NOT NULL,
    [NumFactura]          VARCHAR (32)    NULL,
    [FechaFactura]        DATETIME        NULL,
    [Importe]             DECIMAL (18, 2) NOT NULL,
    [CondicionPago]       VARCHAR (64)    NOT NULL,
    [CondicionPagoDias]   INT             NULL,
    [Proyecto]            VARCHAR (100)   NULL,
    [TipoMoneda]          VARCHAR (8)     NOT NULL,
    [IdCatServicio]       INT             NULL,
    [Servicio]            VARCHAR (100)   NULL,
    [Descripcion]         VARCHAR (128)   NULL,
    [Anotaciones]         VARCHAR (255)   NOT NULL,
    [IdUsr]               INT             NOT NULL,
    [UnidadNegocio]       INT             NOT NULL,
    [CteSolomon]          VARCHAR (16)    NULL,
    [Estado]              INT             NOT NULL,
    [Contrato]            INT             NULL,
    [Factura]             INT             NULL,
    [EnviaCorreoClte]     INT             NULL,
    [Especial]            INT             NULL,
    [Marcado]             INT             NULL,
    [FechaCompromisoPago] DATETIME        NULL,
    CONSTRAINT [PK_cxc_OrdenFactura] PRIMARY KEY CLUSTERED ([IdServicio] ASC, [IdOrdenFactura] ASC)
);

