


CREATE FUNCTION [dbo].[ReportePerfilPagos](@IdEmpresa int, @FEC_INI CHAR(8), @FEC_FIN CHAR(8))
/*ALTER FUNCTION [dbo].[ReportePerfilPagos](@IdUsr int, @FEC_INI CHAR(8), @FEC_FIN CHAR(8)) */
RETURNS @TMPTBL TABLE(IDSOLICITUD INT,
					  FECHAREGISTRO varchar(32),
					  FACTURA VARCHAR(32),
					  FECHAFACTURA DATETIME,
					  IMPORTE DECIMAL(18,2),
					  MONEDA VARCHAR(8),
					  IMPORTEPAGADO DECIMAL(18,2),
					  RFC VARCHAR(20),
					  PROVEEDOR VARCHAR(128),
					  --BANCO VARCHAR(32),
					  --CUENTA VARCHAR(32),
					  --CTA_CLABE VARCHAR(32),
					  ESTADO VARCHAR(32)
					  )
AS
BEGIN
	DECLARE @FECHA_REGISTRO varchar(32)
	DECLARE @FACTURA VARCHAR(32)
	DECLARE @FECHA_FACTURA DATETIME
	DECLARE @IMPORTE DECIMAL(18,2)
	DECLARE @PROVEEDOR VARCHAR(128)
	DECLARE @RFC VARCHAR(20)
	DECLARE @BANCO VARCHAR(32)
	DECLARE @CUENTA VARCHAR(32)
	DECLARE @CTA_CLABE VARCHAR(32)
	DECLARE @ESTADO VARCHAR(32)
	DECLARE @IDSOLICITUD INT
	DECLARE @NUMPAGOS INT
	DECLARE @CONTADOR INT
	DECLARE @IMPORTE_PAGADO DECIMAL(18,2)
	DECLARE @MONEDA VARCHAR(8)

	DECLARE SOLICITUDES_CURSOR CURSOR FAST_FORWARD FOR

		--SELECT DISTINCT(IdSolicitud) FROM dbo.BitacoraSolicitud
			--WHERE  IdUsr=@IdUsr And (estado=40 or estado=50)  And ((FechaRegistro >= @FEC_INI) and(FechaRegistro < DATEADD(dd,1,@FEC_FIN)))

		SELECT DISTINCT(B.IdSolicitud) FROM dbo.BitacoraSolicitud  as B inner join trf_Solicitud  as s
				on S.IdSolicitud=b.IdSolicitud 
			WHERE  S.IdEmpresa =@IdEmpresa And (B.estado=40 or B.estado=50)  And ((B.FechaRegistro >= @FEC_INI) and(B.FechaRegistro < DATEADD(dd,1,@FEC_FIN)))


	OPEN SOLICITUDES_CURSOR 
	FETCH NEXT FROM SOLICITUDES_CURSOR INTO @IDSOLICITUD
	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		SET @FECHA_REGISTRO=''
		SET @FACTURA =''
		SET @FECHA_FACTURA =''
		SET @IMPORTE =0
		SET @PROVEEDOR =''
		SET @RFC =''
		SET @BANCO =''
		SET @CUENTA =''
		SET @CTA_CLABE =''
		SET @IMPORTE_PAGADO =0
		SET @ESTADO=''
		SET @NUMPAGOS=0
		SET @CONTADOR=1

				
		--OBTIENE LOS DATOS DE LA FACTURA
		SELECT  @FACTURA=FACTURA, @FECHA_FACTURA=FECHAFACTURA,@IMPORTE=IMPORTE, @PROVEEDOR=PROVEEDOR,
				@RFC=RFC,@BANCO=BANCO,@CUENTA=CUENTA,@CTA_CLABE=CTACLABE, @MONEDA=MONEDA,
				 @ESTADO=(CASE Estado WHEN  10 THEN 'Solicitud' WHEN  20 THEN 'Autorizacion' WHEN  25 THEN 'Fondos' WHEN  30 THEN 'Captura' WHEN  40 THEN 'PagoParcial' WHEN  50 THEN 'Pagado' WHEN  70 THEN 'Rechazada' END  )
		FROM trf_Solicitud
			WHERE IdSolicitud=@IDSOLICITUD
		
		
		SELECT @IMPORTE_PAGADO = sum(Cantidad) FROM trf_Archivos 
			WHERE IdSolicitud=@IDSOLICITUD AND TIPO=3 AND ((FechaRegistro >= @FEC_INI) and(FechaRegistro < DATEADD(dd,1,@FEC_FIN)))
			  	
		set @FECHA_REGISTRO = CONVERT(VARCHAR(10), CONVERT(DATETIME,@FEC_INI), 103) + ' - ' + CONVERT(VARCHAR(10), CONVERT(DATETIME, @FEC_FIN), 103)
			  	
		
		INSERT INTO @TMPTBL VALUES(@IDSOLICITUD, @FECHA_REGISTRO,@FACTURA,@FECHA_FACTURA,@IMPORTE,@MONEDA,@IMPORTE_PAGADO, @RFC, @PROVEEDOR,@ESTADO)
		FETCH NEXT FROM SOLICITUDES_CURSOR  INTO @IDSOLICITUD
	END		
	CLOSE SOLICITUDES_CURSOR
	DEALLOCATE SOLICITUDES_CURSOR

	RETURN
END



