
CREATE FUNCTION [dbo].[ReporteContabilidad](@IdEmpresa int, @FEC_INI CHAR(8), @FEC_FIN CHAR(8))
RETURNS @TMPTBL TABLE(IDSOLICITUD INT,
					  FECHAREGISTRO DATETIME,
					  FACTURA VARCHAR(32),
					  FECHAFACTURA DATETIME,
					  PROVEEDOR VARCHAR(128),
					  IMPORTE DECIMAL(18,2),
					  MONEDA VARCHAR(8),
					  PROYECTO VARCHAR(32),
					  ESTADO VARCHAR(32),
					  FECHAPAGO DATETIME
					  )
AS
BEGIN
	DECLARE @IDSOLICITUD INT
	DECLARE @FECHA_REGISTRO DATETIME
	DECLARE @FACTURA VARCHAR(32)
	DECLARE @FECHA_FACTURA DATETIME
	DECLARE @PROVEEDOR VARCHAR(128)
	DECLARE @IMPORTE DECIMAL(18,2)
	DECLARE @MONEDA VARCHAR(8)
	DECLARE @PROYECTO VARCHAR(32)
	DECLARE @ESTADO VARCHAR(32)
	DECLARE @FECHA_PAGO DATETIME
	DECLARE @RFC VARCHAR(20)
	
	DECLARE SOLICITUDES_CURSOR CURSOR FAST_FORWARD FOR

		select FECHAREGISTRO ,factura as [NO. FACTURA], FECHAFACTURA,Proveedor,IMPORTE, PROYECTO,    
		CASE Estado WHEN  10 THEN 'Solicitud' WHEN  20 THEN 'Autorizacion' WHEN  30 THEN 'Por pagar' WHEN  40 THEN 'Pago Parcial' WHEN  50 THEN 'Pagado' WHEN  70 THEN 'Rechazada' END  AS ESTADO
		from trf_solicitud 
		where IdEmpresa=@IdEmpresa  
		and estado <>70 
		and  (FechaRegistro >=@FEC_INI and FechaRegistro < DATEADD(dd,1,@FEC_FIN)) 
		order by IdProveedor ,FechaRegistro,FechaFactura 

	OPEN SOLICITUDES_CURSOR 
	FETCH NEXT FROM SOLICITUDES_CURSOR INTO @IDSOLICITUD
	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		SET @FECHA_REGISTRO=''
		SET @FACTURA =''
		SET @FECHA_FACTURA =''
		SET @PROVEEDOR =''
		SET @IMPORTE =0
		SET @MONEDA =''
		SET @PROYECTO =''
		SET @ESTADO=''
		SET @FECHA_PAGO =''
		
		--OBTIENE LOS DATOS DE LA FACTURA
		SELECT @FECHA_REGISTRO=FECHAREGISTRO,  
			   @FACTURA=FACTURA, 
			   @FECHA_FACTURA=FECHAFACTURA,
			   @PROVEEDOR=PROVEEDOR,
			   @IMPORTE=IMPORTE, 
			   @MONEDA=MONEDA,
			   @PROYECTO=PROYECTO,
			   @ESTADO=(CASE Estado WHEN  10 THEN 'Solicitud' WHEN  20 THEN 'Autorizacion' WHEN  25 THEN 'Fondos' WHEN  30 THEN 'Captura' WHEN  40 THEN 'PagoParcial' WHEN  50 THEN 'Pagado' WHEN  70 THEN 'Rechazada' END  )
		FROM trf_Solicitud  WHERE IdSolicitud=@IDSOLICITUD
		
		
		
		IF(@ESTADO='PagoParcial') BEGIN 
			SELECT @FECHA_PAGO=FECHAREGISTRO  FROM BitacoraSolicitud  WHERE IdSolicitud=@IDSOLICITUD AND ESTADO=40
		END
		IF(@ESTADO='Pagado') BEGIN 
			SELECT @FECHA_PAGO=FECHAREGISTRO  FROM BitacoraSolicitud WHERE IdSolicitud=@IDSOLICITUD AND ESTADO=50
		END
		
		INSERT INTO @TMPTBL VALUES(@IDSOLICITUD, @FECHA_REGISTRO,@FACTURA,@FECHA_FACTURA,@PROVEEDOR,@IMPORTE,@MONEDA,@PROYECTO, @ESTADO, @FECHA_PAGO)
		FETCH NEXT FROM SOLICITUDES_CURSOR  INTO @IDSOLICITUD
	END		
	CLOSE SOLICITUDES_CURSOR
	DEALLOCATE SOLICITUDES_CURSOR

	RETURN
END
