UPDATE usuario SET clave='CCvhyRdv0flxNWaveNw0ug==' WHERE idusr=0
UPDATE usuario SET clave='ohKdzhinJAWRFqhPf/9Npg==' WHERE idusr=1
UPDATE usuario SET clave='z7/6zGJZZgmzvBGsdthL/A==' WHERE idusr=2
UPDATE usuario SET clave='hXsiB6YApwpiDnsJQ8wq9w==' WHERE idusr=3
UPDATE usuario SET clave='7ZdlD85bS3Whx4rst8oebg==' WHERE idusr=4
UPDATE usuario SET clave='naZ9wg//wVKLPNy1KFKQvg==' WHERE idusr=5
UPDATE usuario SET clave='ECJrT2vv/m8qwE0PGNygaQ==' WHERE idusr=6
UPDATE usuario SET clave='Nd0ak5qFmgMNDSv8jw3WIg==' WHERE idusr=7
UPDATE usuario SET clave='liapJAeLVj6/FaTMf0BiqA==' WHERE idusr=8
UPDATE usuario SET clave='Gdc2MKSFBT+TqzgUa/e0AA==' WHERE idusr=9
UPDATE usuario SET clave='WU1iLAvWQItlqhXwDiV1MA==' WHERE idusr=10
UPDATE usuario SET clave='HrBd5n/HEWIfk3JlLK2www==' WHERE idusr=11
UPDATE usuario SET clave='oIf9v6w2gAnRP+WQXHxKWQ==' WHERE idusr=12
UPDATE usuario SET clave='wKA8bqasJYk2P1jPv4QQQA==' WHERE idusr=13
UPDATE usuario SET clave='v6SnQokr+t6QfK9g9l9iaQ==' WHERE idusr=14
UPDATE usuario SET clave='i6dEV80/9mFdsSY+94TJEw==' WHERE idusr=15
UPDATE usuario SET clave='liapJAeLVj6/FaTMf0BiqA==' WHERE idusr=16
UPDATE usuario SET clave='gWxkyEKJrUMFQtFMb63KBA==' WHERE idusr=17
UPDATE usuario SET clave='cVumNLU0HNIx/dQmCs0J6A==' WHERE idusr=18
UPDATE usuario SET clave='1DgBx6dtTkQjgJZ8XkEFLA==' WHERE idusr=19
UPDATE usuario SET clave='DUnCUlgQcdIiq0h7okRMvQ==' WHERE idusr=20
UPDATE usuario SET clave='6JnxgvB+2mz2LGUd1ljPDA==' WHERE idusr=21
UPDATE usuario SET clave='liapJAeLVj6/FaTMf0BiqA==' WHERE idusr=22
UPDATE usuario SET clave='k9ymfVbFp+HXj7oKktDEAQ==' WHERE idusr=23
UPDATE usuario SET clave='DI0SO1rTOE1/GIUBrcvVRA==' WHERE idusr=24
UPDATE usuario SET clave='+bvugY40iOo7RsqbVnJtWw==' WHERE idusr=25
UPDATE usuario SET clave='CTtuEYTpSDQRGvqJvZqhdA==' WHERE idusr=26
UPDATE usuario SET clave='NCeHDKYTHibr30Iz8YqY1A==' WHERE idusr=27
UPDATE usuario SET clave='SIh3L1QxOeg6/douEL4a2g==' WHERE idusr=28
UPDATE usuario SET clave='uoquywJjM0oJtJZKbBUQVA==' WHERE idusr=29
UPDATE usuario SET clave='CMZsT9QyNp9juwtN+BCUDQ==' WHERE idusr=30
UPDATE usuario SET clave='7ZdlD85bS3Whx4rst8oebg==' WHERE idusr=31
UPDATE usuario SET clave='O0wUy4IgD2M8JzO2L6VE/w==' WHERE idusr=32
UPDATE usuario SET clave='W8Pg5SBfA+MWeE6TS7pu8w==' WHERE idusr=33
UPDATE usuario SET clave='ZM88BHpPg8mDuaU3F77SwA==' WHERE idusr=34
UPDATE usuario SET clave='DI0SO1rTOE1/GIUBrcvVRA==' WHERE idusr=35
UPDATE usuario SET clave='DI0SO1rTOE1/GIUBrcvVRA==' WHERE idusr=36
UPDATE usuario SET clave='V7cbvKLKKCXpKZqDbR5phA==' WHERE idusr=37
UPDATE usuario SET clave='Hdl8jF48p2Wk/sTdGHg07Q==' WHERE idusr=38
UPDATE usuario SET clave='7ZdlD85bS3Whx4rst8oebg==' WHERE idusr=39
UPDATE usuario SET clave='j9VF84tnwN78mO9qztGmWg==' WHERE idusr=40
UPDATE usuario SET clave='j9VF84tnwN78mO9qztGmWg==' WHERE idusr=41
UPDATE usuario SET clave='Bp9blyZuC/w8eESj3JRRVQ==' WHERE idusr=42
UPDATE usuario SET clave='pftQ11fBXze3W7hAQz7MAw==' WHERE idusr=43
UPDATE usuario SET clave='0ushjVMJ5pFUIGKUGsFcww==' WHERE idusr=44
UPDATE usuario SET clave='DI0SO1rTOE1/GIUBrcvVRA==' WHERE idusr=45
UPDATE usuario SET clave='6KgLWmLAcrHv/kpoBE/kdQ==' WHERE idusr=46
UPDATE usuario SET clave='p3kFQlmJfgHlAPXwdyg6uQ==' WHERE idusr=47
UPDATE usuario SET clave='vYgwyC2Jt9DeO8fZBuZF+w==' WHERE idusr=48
UPDATE usuario SET clave='Ra9UmU35g3XoyW0STL+9kg==' WHERE idusr=49
UPDATE usuario SET clave='2jf8eM3vQfmRL5UPlsLw4w==' WHERE idusr=50
UPDATE usuario SET clave='3L2TLddrKXEqeTb8PTG8Ew==' WHERE idusr=51
UPDATE usuario SET clave='js+jJsmFNDsGrG2GEL0kOQ==' WHERE idusr=52
UPDATE usuario SET clave='kPDFqLLxamlRtFSWv3dMxA==' WHERE idusr=53
UPDATE usuario SET clave='irYeF7Z+BzUkkCvLfI13XA==' WHERE idusr=54
UPDATE usuario SET clave='J9afsi/sDWnou8RhGnC8iA==' WHERE idusr=55
UPDATE usuario SET clave='3cWD55YhOFfvMpxIVQG/uQ==' WHERE idusr=56
UPDATE usuario SET clave='nGk+M5Q3O35ly0lVnHfnpA==' WHERE idusr=57
UPDATE usuario SET clave='A2Yy1Z2rZyUvvgq3uyMCOg==' WHERE idusr=58
